[project]
name = "yahoo"
version = "0.1.0"
description = "An MCP server for Yahoo data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["httpx>=0.28.1", "mcp>=1.1.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
yahoo = "yahoo:main"
